// Package agentcfg loads the daemon's configuration.
//
// Nothing machine-specific is compiled in: the pre-shared key, peer addresses
// and excluded paths all come from configuration, which is what keeps the
// repository free of one user's setup.
package agentcfg

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

// Config is the daemon's full configuration.
type Config struct {
	Mesh      MeshConfig      `toml:"mesh"`
	Dashboard DashboardConfig `toml:"dashboard"`
	Agent     AgentConfig     `toml:"agent"`
	Privacy   PrivacyConfig   `toml:"privacy"`
	Bridge    BridgeConfig    `toml:"bridge"`
}

// BridgeConfig carries records through storage both machines can reach, for
// machines that never share a network.
type BridgeConfig struct {
	// Kind selects a backend. Empty disables the bridge. "filesystem" is the
	// only one implemented; the interface takes others.
	Kind string `toml:"kind"`
	// Path is the directory for the filesystem backend. Point two machines at
	// the same Dropbox, iCloud or NAS folder and they bridge.
	Path string `toml:"path"`
	// Interval is how often to publish and fetch, as a duration string.
	Interval string `toml:"interval"`
}

// MeshConfig holds the shared secret and how peers are found.
type MeshConfig struct {
	// PSK admits this machine to the mesh, seals its records, and unlocks its
	// dashboard. Generated by `init`; never chosen by hand.
	PSK string `toml:"psk"`
	// Peers are addresses that discovery cannot reach — anything across a
	// WireGuard or Tailscale tunnel, since multicast does not cross a
	// point-to-point link. Names are re-resolved on every dial.
	Peers []string `toml:"peers"`
	// Listen is the mesh port. Empty disables inbound peering.
	Listen string `toml:"listen"`
	// Discovery enables the multicast beacon.
	Discovery bool `toml:"discovery"`
	// ExcludeInterfaces keeps beacons off VM bridges and similar.
	ExcludeInterfaces []string `toml:"exclude_interfaces"`
}

// DashboardConfig controls the local web interface.
type DashboardConfig struct {
	// Listen defaults to loopback: http://127.0.0.1 is already a secure
	// context in every browser, with no certificate to manage and no warning.
	Listen string `toml:"listen"`
	// TLSCert and TLSKey enable HTTPS. Empty with a non-loopback Listen means
	// a self-signed certificate is generated and persisted.
	TLSCert string `toml:"tls_cert"`
	TLSKey  string `toml:"tls_key"`
}

// AgentConfig tunes collection.
type AgentConfig struct {
	// PollInterval is how often to look for new data, as a duration string.
	PollInterval string `toml:"poll_interval"`
	// BatchMaxLines bounds records per upload.
	BatchMaxLines int `toml:"batch_max_lines"`
}

// PrivacyConfig withholds data at the source.
type PrivacyConfig struct {
	// ExcludePaths are absolute prefixes that are never read or transmitted.
	ExcludePaths []string `toml:"exclude_paths"`
}

// DefaultPath returns the standard configuration location for this user.
func DefaultPath() (string, error) {
	dir, err := os.UserConfigDir()
	if err != nil {
		return "", fmt.Errorf("agentcfg: locate config dir: %w", err)
	}
	return filepath.Join(dir, "agentic-stats", "config.toml"), nil
}

// Load reads configuration from path, applying environment overrides.
//
// A missing file is not an error: the environment alone is enough to run, which
// keeps container and CI use simple.
func Load(path string) (Config, error) {
	cfg := Config{
		Agent:     AgentConfig{PollInterval: "30s", BatchMaxLines: 2000},
		Dashboard: DashboardConfig{Listen: "127.0.0.1:8899"},
		Mesh:      MeshConfig{Listen: ":8844", Discovery: true},
	}

	data, err := os.ReadFile(path)
	switch {
	case err == nil:
		if err := toml.Unmarshal(data, &cfg); err != nil {
			return Config{}, fmt.Errorf("agentcfg: parse %s: %w", path, err)
		}
	case errors.Is(err, os.ErrNotExist):
		// Fall through to environment-only configuration.
	default:
		return Config{}, fmt.Errorf("agentcfg: read %s: %w", path, err)
	}

	// The PSK may come from the environment so a container or CI run needs no
	// file on disk.
	if v := os.Getenv("AGENTIC_STATS_PSK"); v != "" {
		cfg.Mesh.PSK = v
	}
	return cfg, nil
}

// Save writes configuration to path with owner-only permissions, creating the
// directory if needed. The file holds the pre-shared key, so the mode matters.
func Save(path string, cfg Config) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("agentcfg: create config dir: %w", err)
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return fmt.Errorf("agentcfg: open %s: %w", path, err)
	}
	if err := toml.NewEncoder(f).Encode(cfg); err != nil {
		return errors.Join(fmt.Errorf("agentcfg: write %s: %w", path, err), f.Close())
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("agentcfg: close %s: %w", path, err)
	}
	// The 0600 above is honoured on Unix and ignored on Windows, where the
	// equivalent has to be spelled out as an access list.
	return restrictToOwner(path)
}
